/**:
  ros__parameters:
    wheel_radius : 0.05
    wheel_position_x : [+0.45, -0.45, -0.45, +0.45]
    wheel_position_y : [+0.45, +0.45, -0.45, -0.45]
    wheel_angle_deg: [-45.0, +45.0, +135.0, -135.0]