/**:
  ros__parameters:
    chassis_type : "omni"
    wheel_radius : 0.05
    wheel_names : ["omni_wheel_0", "omni_wheel_1", "omni_wheel_2", "omni_wheel_3"]
    wheel_base_names: ["omni_wheel_0_base", "omni_wheel_1_base", "omni_wheel_2_base", "omni_wheel_3_base"]