/**:
  ros__parameters:
    control_frequency: 100.0
    lookahead_time: 0.1
    min_lookahead_distance: 0.09
    max_lookahead_distance: 1.0
    angle_speed_p: 1.0
    curvature_decceleration_p: 0.1
    min_curvature_speed_m_s: 0.3
    angle_decceleration_p: 1.5
    max_acceleration_xy_m_s2_: 10.0
    max_speed_xy_m_s: 7.0
    min_speed_xy_m_s: 0.1
    max_speed_yaw_deg_s: 200.0
    min_speed_yaw_deg_s: 70.0
    max_acceleration_yaw_deg_s2: 1000.0
    goal_deceleration_m_s2: 5.0
    goal_deceleration_distance_p: 1.0
    goal_position_tolerance_m: 0.05
    goal_yaw_tolerance_deg: 5.0
    goal_speed_tolerance_xy_m_s: 2.0
    goal_speed_tolerance_yaw_deg_s: 60.0
