/**:
  ros__parameters:
    frequency: 100.0
    lookahead_time_s: 0.3
    min_lookahead_distance_m: 0.1
    max_lookahead_distance_m: 1.0
    yaw_speed_p: 1.0
    curvature_deceleration_p: 0.0
    min_curvature_speed_m_s: 0.1
    yaw_deceleration_p: 1.0
    max_acceleration_xy_m_s2_: 10.0
    max_speed_xy_m_s: 7.0
    min_speed_xy_m_s: 0.1
    max_speed_yaw_deg_s: 180.0
    min_speed_yaw_deg_s: 1.0
    max_acceleration_yaw_deg_s2: 1000.0
    goal_deceleration_m_s2: 5.0
    goal_deceleration_distance_p: 2.0
    goal_position_tolerance_m: 0.02
    goal_yaw_tolerance_deg: 5.0
    goal_speed_tolerance_xy_m_s: 0.1
    goal_speed_tolerance_yaw_deg_s: 10.0
