/**:
  ros__parameters:
    initial_pose_x: 1.0
    initial_pose_y: 1.0
    initial_pose_yaw_deg: 0.0
    frequency: 100.0
    joint_names : ["swerve_wheel_0", "swerve_wheel_1", "swerve_wheel_2", "swerve_wheel_3",
                   "swerve_steer_0", "swerve_steer_1", "swerve_steer_2", "swerve_steer_3"]
    control_modes : ["speed", "speed", "speed", "speed",
                     "position", "position", "position", "position"]
    initial_positions : [0.0, 0.0, 0.0, 0.0,
                         0.0, 0.0, 0.0, 0.0]
    joint_position_tau : [0.1, 0.1, 0.1, 0.1,
                          0.1, 0.1, 0.1, 0.1]
    joint_velocity_tau : [0.1, 0.1, 0.1, 0.1,
                          0.1, 0.1, 0.1, 0.1]
    joint_velocity_max : [60.0, 60.0, 60.0, 60.0,
                          10.0, 10.0, 10.0, 10.0]