name: autofix

on:
  push:

permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/nitic-robot-club/natto_library:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run clang-format
        run: |
          find src -regex '.*\.\(cpp\|hpp\|h\)' -exec clang-format -i {} +

      - name: Commit and push autofix
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git config --global --add safe.directory .
          
          if ! git diff --quiet; then
            git add .
            git commit -m "style(clang-format): autofix" || true
            git push origin HEAD:${{ github.head_ref }}
          else
            echo "No changes to commit."
          fi