name: autofix and build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix_and_build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/nitic-robot-club/natto_library:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Run clang-format
        run: |
          find src -regex '.*\.\(cpp\|hpp\|h\)' -exec clang-format -i {} +

      - name: Commit and push autofix
        run: |
          ls
          pwd
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          # commit される変更があるか確認
          if ! git diff --quiet; then
            git add -u
            git commit -m "style(clang-format): autofix" || true

            # pull_requestイベントでは、このトークンがフォーク先に対してwrite可能
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.head_ref }}
          else
            echo "No changes to commit."
          fi

      - name: Build test
        id: build_test
        working-directory: /home/nitic-robot-club/natto_library
        run: |
          . /opt/ros/humble/setup.sh
          colcon build --symlink-install

      - name: build_test command success
        if: steps.build_test.outcome == 'success'
        run: echo "result - success"

      - name: build_test command failure
        if: steps.build_test.outcome == 'failure'
        run: echo "result - failure" && exit 1
