name: autofix and build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix_and_build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/nitic-robot-club/natto_library:latest

    steps:
      - name: Checkout target
        working-directory: /home/nitic-robot-club/natto_library
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "Fetching PR source..."
            git fetch https://github.com/${{ github.event.pull_request.head.repo.full_name }} \
              ${{ github.event.pull_request.head.ref }} --depth=1
            git checkout FETCH_HEAD
          else
            echo "Fetching main branch..."
            git fetch origin main --depth=1
            git checkout main
          fi

      - name: Run clang-format
        working-directory: /home/nitic-robot-club/natto_library
        run: |
          find src -regex '.*\.\(cpp\|hpp\|h\)' -exec clang-format -i {} +

      - name: Commit and push autofix
        working-directory: /home/nitic-robot-club/natto_library
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          if ! git diff --quiet; then
            git add -u
            git commit -m "style(clang-format): autofix" || true

            if [ "${{ github.event_name }}" = "pull_request" ]; then
              echo "Pushing to fork branch..."
              git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.event.pull_request.head.repo.full_name }}.git HEAD:${{ github.head_ref }}
            else
              echo "Pushing to main..."
              git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
            fi
          else
            echo "No changes to commit."
          fi

      - name: Build test
        id: build_test
        working-directory: /home/nitic-robot-club/natto_library
        run: |
          . /opt/ros/humble/setup.sh
          colcon build --symlink-install

      - name: build_test command success
        if: steps.build_test.outcome == 'success'
        run: echo "result - success"

      - name: build_test command failure
        if: steps.build_test.outcome == 'failure'
        run: echo "result - failure" && exit 1
