name: autofix and build

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix_and_build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/nitic-robot-club/natto_library:latest

    steps:
      # --- checkout ---
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}

      # --- git設定 ---
      - name: Set git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      # --- auto-fix ---
      - name: Run clang-format
        run: |
          find src -regex '.*\.\(cpp\|hpp\|h\)' -exec clang-format -i {} +

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style(clang-format): autofix"
          add_options: -u
          branch: ${{ github.head_ref || github.ref_name }}

      # --- build & test ---
      - name: Build test
        run: |
          . /opt/ros/humble/setup.sh
          colcon build --symlink-install
